### ISSUE TITLE
What was your best programming moment?

### ISSUE THREAD

**Issue by sindresorhus** [callmecavs/ama#1]

**Comment by callmecavs** [comment]
Definitely when I released [Layzr](https://github.com/callmecavs/layzr.js) v1.0.0, back in early 2015.

It was my first major open source contribution, and I was absolutely blown away by the reception. It hit the trending charts, and got something like 2500 stars in the first week.

It totally changed my outlook - and my confidence - in terms of my ability to create quality open source solutions to common frontend development problems. It was also my first major venture into writing vanilla JS, and it was a much need affirmation of the fact that I was doing an okay job at it.

It encouraged me to continue contributing to the community, and was the beginning of me learning the "intangibles" of open source - how to maintain a project, how to handle issues/pull requests, etc.

It was the first piece of code that I was really proud to show people, which looking back on it now definitely impacted my career.

**Comment by herredro-xw** [comment]
beautiful
