### ISSUE TITLE
What kind of sock person are you?

### ISSUE THREAD

**Issue by sindresorhus** [callmecavs/ama#3]
![image](https://cloud.githubusercontent.com/assets/170270/15268503/19937526-1a0b-11e6-97e6-dcb4926f8ce5.png)
### or

![image](https://cloud.githubusercontent.com/assets/170270/15268504/214f19a0-1a0b-11e6-94f4-b4bfd65bdfef.png)

**Comment by callmecavs** [comment]
Given only those 2 options: I'd have to pick the second pair.

Given any options: I wear shorts pretty much every day of the year, and in light of that, I typically wear black "no show"-cut socks.  Like these:

![Socks](https://media.midwayusa.com/productimages/880x660/Primary/168/168056.jpg)
